In [49]:
import numpy as np

from sklearn.preprocessing import StandardScaler


In [50]:
def PCA(X , num_components):
    '''
    input:
    X -> is 2D list Data which we have to apply PCA
    k -> num_dimensions in which we want to reduce
    
    output:
    X_reduced -> a 2-D numpy array, containing the reduced matrix by k dimensions
    '''
    
    #Step-1
    X_meaned = (X-np.mean(X , axis = 0)) 
    #Step-2
    cov_mat = np.cov(X_meaned.T)
    print(X_meaned.T)
    #Step-3
    eigen_values , eigen_vectors = np.linalg.eig(cov_mat)
    print(cov_mat)
    print(eigen_values)
    print(eigen_vectors)
     
    #Step-4
    sorted_index = np.argsort(eigen_values)[::-1]
    sorted_eigenvectors = eigen_vectors[:,sorted_index]
     
    #Step-5
    eigenvector_subset = sorted_eigenvectors[:,:num_components]
     
    #Step-6
    X_reduced = np.dot(X_meaned,eigenvector_subset)
    return X_reduced.round(2)

In [51]:
X = [[1,2,3,4],[5,6,7,8]]
num_components = 2

In [22]:
PCA(X, num_components)

[[-2.  2.]
 [-2.  2.]
 [-2.  2.]
 [-2.  2.]]
[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]
[-3.55271368e-15  3.20000000e+01  0.00000000e+00  0.00000000e+00]
[[-0.8660254   0.5         0.          0.        ]
 [ 0.28867513  0.5        -0.57735027 -0.57735027]
 [ 0.28867513  0.5         0.78867513 -0.21132487]
 [ 0.28867513  0.5        -0.21132487  0.78867513]]


array([[-4.,  0.],
       [ 4.,  0.]])

In [23]:
X = np.matrix(X)

In [24]:
X

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [25]:
#for i in range(0, len(X)):
#    m = np.mean(X[i])
#    st = np.std(X[i])
#    for j in range(0, len(X[i])):
#        X[i][j] = (X[i][j] - m) / st

In [26]:
X

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [27]:
#X_s =  StandardScaler().fit_transform(X)

In [28]:
X_s = X - np.mean(X , axis = 0)

In [29]:
X_s

matrix([[-2., -2., -2., -2.],
        [ 2.,  2.,  2.,  2.]])

In [30]:
X = X_s

In [31]:
covarm = np.matmul(X.T, X)

In [32]:
covarm

matrix([[8., 8., 8., 8.],
        [8., 8., 8., 8.],
        [8., 8., 8., 8.],
        [8., 8., 8., 8.]])

In [33]:
covarm.shape

(4, 4)

In [34]:
from scipy.linalg import eigh

va, vec = eigh(covarm, eigvals = (2,3))

In [35]:
va

array([2.08016574e-15, 3.20000000e+01])

In [36]:
vec

array([[ 0.72203998, -0.5       ],
       [ 0.21015455, -0.5       ],
       [-0.46609727, -0.5       ],
       [-0.46609727, -0.5       ]])

In [37]:
vec.shape

(4, 2)

In [38]:
vec.shape

(4, 2)

In [39]:
vec = vec.T

In [40]:
vec

array([[ 0.72203998,  0.21015455, -0.46609727, -0.46609727],
       [-0.5       , -0.5       , -0.5       , -0.5       ]])

In [41]:
X 

matrix([[-2., -2., -2., -2.],
        [ 2.,  2.,  2.,  2.]])

In [42]:
np.matmul(vec, X.T)

matrix([[ 2.22044605e-16, -2.22044605e-16],
        [ 4.00000000e+00, -4.00000000e+00]])

In [43]:
a = -0

In [44]:
a 

0